apiVersion: v1
kind: Service
metadata:
  name: shortlife-receiver-service
spec:
  selector:
    app: shortlife-receiver
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
