apiVersion: v1
kind: Service
metadata:
  name: go-graphite-service
spec:
  selector:
    app: go-graphite
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: carbon
      protocol: TCP
      port: 2003
      targetPort: 2003
    - name: pickle
      protocol: TCP
      port: 2004
      targetPort: 2004
  type: LoadBalancer
